[package]
name = "tetris"
version = "0.1.0"
authors = ["Nikolai Brendler <nbrendler@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.0-rc.0"
nalgebra = {version = "0.18", features = ["mint"] }
rand = "0.6"
gfx = "0.18.1"
